test_data_10 = [["start", "A"],
["start", "b"],
["A", "c"],
["A", "b"],
["b", "d"],
["A", "end"],
["b", "end"]]

test_data_19 = [["dc", "end"],
["HN", "start"],
["start", "kj"],
["dc", "start"],
["dc", "HN"],
["LN", "dc"],
["HN", "end"],
["kj", "sa"],
["kj", "HN"],
["kj", "dc"]]

test_data_226 = [["fs", "end"],
["he", "DX"],
["fs", "he"],
["start", "DX"],
["pj", "DX"],
["end", "zg"],
["zg", "sl"],
["zg", "pj"],
["pj", "he"],
["RW", "he"],
["fs", "DX"],
["pj", "RW"],
["zg", "RW"],
["start", "pj"],
["he", "WI"],
["zg", "he"],
["pj", "fs"],
["start", "RW"]]

data = [["XW", "ed"],
["cc", "tk"],
["eq", "ed"],
["ns", "eq"],
["cc", "ed"],
["LA", "kl"],
["II", "tk"],
["LA", "end"],
["end", "II"],
["SQ", "kl"],
["cc", "kl"],
["XW", "eq"],
["ed", "LA"],
["XW", "tk"],
["cc", "II"],
["tk", "LA"],
["eq", "II"],
["SQ", "start"],
["LA", "start"],
["XW", "end"],
["ed", "tk"],
["eq", "JR"],
["start", "kl"],
["ed", "II"],
["SQ", "tk"]]